### ISSUE TITLE
final project feedback

### ISSUE THREAD

**Issue by fodisi** [lambo4jos/blockchain-developer-bootcamp-final-project#1]
Hi @, I'm a mentor of the consensy bootcamp responsible for grading your project.
Congratulations, your Final Project passed! We'll be approving it on the course itself in a week or two, but here's your feedback in the meanwhile:

Frontend Comments
meets the requiremements. Consider checking the network the user is connected to, and giving an alert if the wrong one.

Testing Comments
Nice unit test coverage. Well done

Design and Security Comments
nice to see leveraging on OpenZeppelin and all the thought in the design pattern decisions + avoiding common attacks

Congrats

**Comment by lambo4jos** [comment]
Hi @fodisi, thank you for the message!

All great comments. I will consider the frontend idea for implementation. I ran out of time to polish the frontend and have been waiting for the course to complete before I do any updates.

Thank you for making this such a great program to be a part of!

Best
